import { Lead, ContentItem, ReviewTask, Notification, SkillFile, FunnelStage, CalendarEvent, Scene, ChannelPerformance } from "./types";

// ─── LEADS ───
export const leads: Lead[] = [
  {
    id: "lead_001",
    name: "Sarah Mitchell",
    email: "sarah.mitchell@email.com",
    country: "United States",
    age: 42,
    avatar: "/workbench/avatars/sarah.jpg",
    primaryGoals: ["Sleep Reset", "Stress Recovery"],
    source: "Instagram Reels",
    campaign: "POV: Arrive in China",
    status: "qualified",
    riskLevel: "low",
    intentScore: 92,
    lastActivity: "2 hours ago",
    nextAction: "Send video consultation link",
    budget: "$3,000 - $5,000",
    aiSummary: "High-intent lead from US corporate sector. Primary goals: sleep reset and stress recovery. Concerned about language barrier and acupuncture safety. No major medical red flags. Planning September visit. Previously tried sleep supplements with limited results.",
    riskNotes: ["Taking sleep supplements — follow up on dosage", "Do not promise cure outcomes"],
    intakeDetails: {
      goals: "Sleep reset, stress recovery, whole-person balance",
      concerns: "Language barrier, safety of acupuncture, not wanting tourist-group experience",
      timeline: "Planning visit in September 2026",
      previousExperience: "Tried sleep supplements, meditation apps, corporate wellness programs",
      medicalConditions: ["Chronic insomnia (self-reported)", "High stress levels"],
      medications: ["Melatonin 3mg nightly", "Magnesium supplement"],
      preferredContact: "Email",
    },
    timeline: [
      { date: "Apr 26, 2026", action: "Submitted intake form via Reels CTA", by: "Lead" },
      { date: "Apr 26, 2026", action: "AI risk assessment completed — LOW risk", by: "AI Agent" },
      { date: "Apr 27, 2026", action: "Flagged for human review — sleep supplement interaction", by: "AI Agent" },
      { date: "Apr 27, 2026", action: "Reviewed and approved by founder", by: "You" },
    ],
    sourceAttribution: {
      campaign: "POV Experience Series Q2",
      contentItem: "POV: Shanghai arrival for a 5-day Hangzhou reset",
      channel: "Instagram Reels",
      utmSource: "instagram",
      utmMedium: "reels",
      utmCampaign: "pov_arrive_china_0426",
    },
  },
  {
    id: "lead_002",
    name: "James Chen",
    email: "j.chen@techflow.io",
    country: "Singapore",
    age: 35,
    avatar: "/workbench/avatars/james.jpg",
    primaryGoals: ["Stress Recovery"],
    source: "LinkedIn",
    campaign: "Why Eastaura Doesn't Promise Cures",
    status: "contacted",
    riskLevel: "medium",
    intentScore: 74,
    lastActivity: "5 hours ago",
    nextAction: "Follow up on medical history form",
    budget: "$2,000 - $4,000",
    aiSummary: "Tech executive from Singapore. Interested in stress recovery but hesitant about TCM credibility. Strong analytical profile. Asked about clinical evidence. Medium risk due to skepticism that may lead to early churn if expectations are not carefully managed.",
    riskNotes: ["Skeptical about TCM — needs evidence-based framing", "High expectation for measurable outcomes"],
    intakeDetails: {
      goals: "Burnout recovery, regain focus and energy",
      concerns: "Scientific validity of TCM, ROI on wellness retreat",
      timeline: "Flexible, Q3 2026",
      previousExperience: "Executive coaching, biomarker testing",
      medicalConditions: ["Work-related burnout"],
      medications: ["None reported"],
      preferredContact: "LinkedIn DM + Email",
    },
    timeline: [
      { date: "Apr 25, 2026", action: "Submitted intake form", by: "Lead" },
      { date: "Apr 25, 2026", action: "AI summary generated", by: "AI Agent" },
      { date: "Apr 26, 2026", action: "Initial follow-up email drafted", by: "AI Agent" },
    ],
    sourceAttribution: {
      campaign: "Trust & Transparency Series",
      contentItem: "Why Eastaura Doesn't Promise Cures",
      channel: "LinkedIn",
      utmSource: "linkedin",
      utmMedium: "post",
      utmCampaign: "trust_no_cure_0420",
    },
  },
  {
    id: "lead_003",
    name: "Elena Rossi",
    email: "elena.rossi@designstudio.it",
    country: "Italy",
    age: 51,
    avatar: "/workbench/avatars/elena.jpg",
    primaryGoals: ["Whole-Person Balance", "Sleep Reset"],
    source: "YouTube Shorts",
    campaign: "Sleep Reset Explained",
    status: "new",
    riskLevel: "high",
    intentScore: 68,
    lastActivity: "1 hour ago",
    nextAction: "Risk review required before contact",
    budget: "$4,000 - $6,000",
    aiSummary: "Designer from Italy. Interested in holistic balance and sleep. High risk flagged due to reported heart condition and blood pressure medication. Requires medical boundary review before any consultation can be offered.",
    riskNotes: ["Heart condition reported — requires medical boundary check", "On blood pressure medication — TCM interaction assessment needed", "Do NOT provide medical advice"],
    intakeDetails: {
      goals: "Holistic wellness, sleep improvement, life balance",
      concerns: "Safety due to heart condition, travel to China",
      timeline: "October 2026",
      previousExperience: "Ayurveda retreat in India, yoga teacher training",
      medicalConditions: ["Hypertension", "Mild heart arrhythmia (self-reported)"],
      medications: ["Lisinopril", "Metoprolol"],
      preferredContact: "Email",
    },
    timeline: [
      { date: "Apr 27, 2026", action: "Submitted intake form via YouTube Shorts", by: "Lead" },
      { date: "Apr 27, 2026", action: "AI flagged HIGH RISK — medical conditions detected", by: "AI Agent" },
    ],
    sourceAttribution: {
      campaign: "Sleep Education Series",
      contentItem: "Sleep Reset Explained",
      channel: "YouTube Shorts",
      utmSource: "youtube",
      utmMedium: "shorts",
      utmCampaign: "sleep_reset_0415",
    },
  },
  {
    id: "lead_004",
    name: "David Park",
    email: "david.park@outlook.kr",
    country: "South Korea",
    age: 29,
    avatar: "/workbench/avatars/david.jpg",
    primaryGoals: ["Stress Recovery"],
    source: "TikTok",
    campaign: "5-Day Shanghai + Hangzhou Pilot Flow",
    status: "nurture",
    riskLevel: "low",
    intentScore: 45,
    lastActivity: "3 days ago",
    nextAction: "Add to nurture sequence — budget not ready",
    budget: "$1,000 - $2,000",
    aiSummary: "Young professional from Seoul. Interested in stress recovery but budget constraint noted. Currently saving for experience. Low immediate conversion probability but good long-term nurture candidate. No medical risks.",
    riskNotes: [],
    intakeDetails: {
      goals: "Stress recovery, mental clarity",
      concerns: "Budget, travel logistics",
      timeline: "2027 or later",
      previousExperience: "Local spa treatments, gym membership",
      medicalConditions: [],
      medications: [],
      preferredContact: "Email",
    },
    timeline: [
      { date: "Apr 20, 2026", action: "Submitted intake form", by: "Lead" },
      { date: "Apr 21, 2026", action: "AI scored intent at 45 — nurture recommended", by: "AI Agent" },
    ],
    sourceAttribution: {
      campaign: "Experience Overview",
      contentItem: "5-Day Shanghai + Hangzhou Pilot Flow",
      channel: "TikTok",
      utmSource: "tiktok",
      utmMedium: "video",
      utmCampaign: "experience_5d4n_0410",
    },
  },
  {
    id: "lead_005",
    name: "Anna Kowalski",
    email: "anna.k@wellness.pl",
    country: "Poland",
    age: 38,
    avatar: "/workbench/avatars/anna.jpg",
    primaryGoals: ["Sleep Reset", "Whole-Person Balance"],
    source: "Newsletter",
    campaign: "Weekly Brief — Sleep Edition",
    status: "consultation_booked",
    riskLevel: "low",
    intentScore: 88,
    lastActivity: "12 hours ago",
    nextAction: "Prepare for video call on Apr 29",
    budget: "$3,500 - $5,500",
    aiSummary: "Wellness practitioner from Poland. High intent, clear goals, comfortable with holistic approaches. Already booked consultation. Low risk profile. Good fit for premium 5-day program.",
    riskNotes: [],
    intakeDetails: {
      goals: "Sleep reset, energy restoration, learn TCM self-care",
      concerns: "None significant",
      timeline: "May 2026",
      previousExperience: "Naturopathy training, yoga instruction",
      medicalConditions: [],
      medications: [],
      preferredContact: "Email + Zoom",
    },
    timeline: [
      { date: "Apr 15, 2026", action: "Submitted intake form", by: "Lead" },
      { date: "Apr 15, 2026", action: "AI summary — HIGH INTENT, LOW RISK", by: "AI Agent" },
      { date: "Apr 16, 2026", action: "Follow-up email sent", by: "AI Agent" },
      { date: "Apr 18, 2026", action: "Video consultation booked for Apr 29", by: "Lead" },
    ],
    sourceAttribution: {
      campaign: "Newsletter Sleep Series",
      contentItem: "Weekly Brief — Sleep Edition",
      channel: "Newsletter",
      utmSource: "newsletter",
      utmMedium: "email",
      utmCampaign: "newsletter_sleep_apr3",
    },
  },
  {
    id: "lead_006",
    name: "Marcus Weber",
    email: "m.weber@consulting.de",
    country: "Germany",
    age: 47,
    avatar: "/workbench/avatars/marcus.jpg",
    primaryGoals: ["Stress Recovery", "Sleep Reset"],
    source: "LinkedIn",
    campaign: "Founder's Story",
    status: "proposal_sent",
    riskLevel: "low",
    intentScore: 85,
    lastActivity: "1 day ago",
    nextAction: "Follow up on proposal response",
    budget: "$5,000 - $8,000",
    aiSummary: "Senior consultant from Germany. High budget, clear timeline (June 2026). Already received personalized proposal. Interested in executive-focused program with privacy and discretion.",
    riskNotes: [],
    intakeDetails: {
      goals: "Executive burnout recovery, sleep restoration",
      concerns: "Privacy, efficiency of program, dietary requirements",
      timeline: "June 2026",
      previousExperience: "Luxury spa retreats, executive wellness programs",
      medicalConditions: ["Mild sleep apnea (using CPAP)"],
      medications: [],
      preferredContact: "Email",
    },
    timeline: [
      { date: "Apr 10, 2026", action: "Submitted intake form", by: "Lead" },
      { date: "Apr 11, 2026", action: "Video consultation completed", by: "You" },
      { date: "Apr 14, 2026", action: "Personalized proposal sent", by: "AI Agent" },
    ],
    sourceAttribution: {
      campaign: "Founder Series",
      contentItem: "Founder's Story — Why I Built Eastaura",
      channel: "LinkedIn",
      utmSource: "linkedin",
      utmMedium: "post",
      utmCampaign: "founder_story_0405",
    },
  },
  {
    id: "lead_007",
    name: "Yuki Tanaka",
    email: "yuki.t@creative.jp",
    country: "Japan",
    age: 33,
    avatar: "/workbench/avatars/yuki.jpg",
    primaryGoals: ["Whole-Person Balance"],
    source: "Instagram Reels",
    campaign: "No Chinese Required",
    status: "contacted",
    riskLevel: "low",
    intentScore: 70,
    lastActivity: "8 hours ago",
    nextAction: "Answer questions about dietary accommodations",
    budget: "$2,500 - $4,000",
    aiSummary: "Creative director from Tokyo. Interested in whole-person balance. Asked about Japanese/English bilingual support and pescatarian meal options. Good intent, no medical risks.",
    riskNotes: [],
    intakeDetails: {
      goals: "Creative renewal, work-life balance, cultural immersion",
      concerns: "Language support, dietary needs (pescatarian)",
      timeline: "August 2026",
      previousExperience: "Onsen retreats, meditation practice",
      medicalConditions: [],
      medications: [],
      preferredContact: "Email",
    },
    timeline: [
      { date: "Apr 24, 2026", action: "Submitted intake form", by: "Lead" },
      { date: "Apr 24, 2026", action: "AI drafted personalized email", by: "AI Agent" },
      { date: "Apr 25, 2026", action: "Email approved and sent", by: "You" },
    ],
    sourceAttribution: {
      campaign: "Barrier Breaker Series",
      contentItem: "No Chinese Required — Full English Support",
      channel: "Instagram Reels",
      utmSource: "instagram",
      utmMedium: "reels",
      utmCampaign: "no_chinese_required_0420",
    },
  },
  {
    id: "lead_008",
    name: "Olivia Brown",
    email: "olivia.brown@health.au",
    country: "Australia",
    age: 55,
    avatar: "/workbench/avatars/olivia.jpg",
    primaryGoals: ["Sleep Reset"],
    source: "Blog",
    campaign: "What Happens in Your First TCM Consultation",
    status: "new",
    riskLevel: "medium",
    intentScore: 60,
    lastActivity: "6 hours ago",
    nextAction: "Review medical history — menopause-related sleep issues",
    budget: "$3,000 - $4,500",
    aiSummary: "Health professional from Australia. Investigating TCM for menopause-related sleep disruption. Medium risk due to hormone therapy. Needs careful medical boundary framing.",
    riskNotes: ["On HRT — clarify that Eastaura does not replace medical treatment", "Menopause-related symptoms require sensitive language"],
    intakeDetails: {
      goals: "Natural sleep support during menopause transition",
      concerns: "Safety with HRT, evidence for TCM in menopause",
      timeline: "September 2026",
      previousExperience: "Integrative medicine practice, acupuncture referral",
      medicalConditions: ["Menopause transition", "Occasional hot flashes"],
      medications: ["HRT (estradiol/progesterone)"],
      preferredContact: "Email",
    },
    timeline: [
      { date: "Apr 27, 2026", action: "Submitted intake form", by: "Lead" },
      { date: "Apr 27, 2026", action: "AI summary generated", by: "AI Agent" },
    ],
    sourceAttribution: {
      campaign: "Education Series",
      contentItem: "What Happens in Your First TCM Consultation",
      channel: "Blog",
      utmSource: "blog",
      utmMedium: "article",
      utmCampaign: "first_consultation_0325",
    },
  },
];

// ─── CONTENT ITEMS ───
export const contentItems: ContentItem[] = [
  {
    id: "content_001",
    title: "POV: Shanghai arrival, Hangzhou reset",
    type: "short_video_script",
    channel: "Instagram Reels",
    campaign: "Shanghai -> Hangzhou Pilot Series",
    cta: "Start Safety Intake",
    complianceStatus: "approved",
    publishStatus: "scheduled",
    sourceCode: "reels_sha_hgh_reset_001",
    performanceNotes: "Primary cold-start asset. Translates the trip from foreign/unknown into calm, guided, and safety-screened.",
    createdAt: "2026-04-20",
    updatedAt: "2026-04-26",
    thumbnail: "/workbench/thumbs/scene-arrival.jpg",
    body: "[Scene 1: 0-3s] POV shot: landing in Shanghai. Text overlay: 'You came to China to finally slow down.'\n[Scene 2: 3-8s] Private transfer toward Hangzhou. Soft highway light, water, tea hills.\n[Scene 3: 8-15s] Arrival tea and translated orientation. No packed tourist schedule.\n[Scene 4: 15-20s] TCM-informed wellness consultation with interpreter. Clear non-medical boundary.\n[Scene 5: 20-25s] Quiet pavilion at sunset. Text: '5 days. Safety screened. Human guided.'\n[CTA] Start the safety intake for the pilot retreat.",
    topics: ["POV", "Shanghai Arrival", "Hangzhou Reset"],
    platforms: ["Instagram", "TikTok", "YouTube Shorts"],
  },
  {
    id: "content_002",
    title: "Why Eastaura Doesn't Promise Cures",
    type: "linkedin_post",
    channel: "LinkedIn",
    campaign: "Trust & Transparency Series",
    cta: "Read Full Position Paper",
    complianceStatus: "approved",
    publishStatus: "published",
    sourceCode: "linkedin_no_cure_001",
    performanceNotes: "Highest LinkedIn engagement this quarter. 47 shares from wellness professionals.",
    createdAt: "2026-04-15",
    updatedAt: "2026-04-18",
    thumbnail: "/workbench/thumbs/linkedin.jpg",
    body: "Three reasons Eastaura never promises 'cures':\n\n1. TCM is a system of balance, not a drug protocol\n2. Every body responds differently to herbal support and acupuncture\n3. The retreat is an experience of reset, not a medical intervention\n\nWhat we DO promise: a structured 5-day immersion designed by licensed practitioners, in a setting that removes the stressors preventing your recovery.\n\nThe rest is your body's own intelligence.",
    topics: ["Trust", "Medical Boundary", "Transparency"],
    platforms: ["LinkedIn"],
  },
  {
    id: "content_003",
    title: "Stress Recovery Is Not a Vacation",
    type: "short_video_script",
    channel: "TikTok",
    campaign: "Barrier Breaker Series",
    cta: "Learn the Difference",
    complianceStatus: "flagged",
    publishStatus: "review",
    sourceCode: "tiktok_stress_not_vacay_001",
    performanceNotes: "Flagged for medical-adjacent language. Revision needed before publish.",
    createdAt: "2026-04-22",
    updatedAt: "2026-04-26",
    thumbnail: "/workbench/thumbs/scene-hotel.jpg",
    body: "[Scene 1: 0-3s] Split screen: beach resort vs. quiet clinic. Text: 'This is a vacation. This is recovery.'\n[Scene 2: 3-8s] Explain the difference: vacation avoids stress. Recovery addresses it.\n[Scene 3: 8-15s] Show daily rhythm at Eastaura: pulse check, herbal tea, structured rest, acupuncture, evening reflection.\n[Scene 4: 15-20s] Practitioner explains: 'We don't distract you from burnout. We give your nervous system space to downregulate.'\n[CTA] 'Is this what you need?' — link to self-assessment.",
    topics: ["Stress Recovery", "Vacation vs Recovery"],
    platforms: ["TikTok", "Instagram Reels"],
  },
  {
    id: "content_004",
    title: "What Happens in Your First TCM Consultation",
    type: "blog",
    channel: "Blog",
    campaign: "Education Series",
    cta: "Book a Free Discovery Call",
    complianceStatus: "approved",
    publishStatus: "published",
    sourceCode: "blog_first_consult_001",
    performanceNotes: "Top organic search traffic driver. Avg. 4:30 time on page.",
    createdAt: "2026-03-20",
    updatedAt: "2026-04-01",
    thumbnail: "/workbench/thumbs/scene-consult.jpg",
    body: "Your first consultation is not a sales pitch. It is a diagnostic conversation.\n\nStep 1: Intake form (submitted 48 hours before)\nStep 2: Pulse diagnosis and tongue observation (15 minutes)\nStep 3: Conversation about sleep, digestion, stress patterns, and goals (30 minutes)\nStep 4: Personalized retreat protocol drafted (delivered within 24 hours)\n\nNo pressure. No upsell. Just clarity on whether Eastaura is the right fit for your situation.",
    topics: ["First Consultation", "TCM Process", "Education"],
    platforms: ["Blog", "Newsletter"],
  },
  {
    id: "content_005",
    title: "Sleep Reset Explained",
    type: "short_video_script",
    channel: "YouTube Shorts",
    campaign: "Sleep Education Series",
    cta: "Download Sleep Guide",
    complianceStatus: "approved",
    publishStatus: "published",
    sourceCode: "shorts_sleep_reset_001",
    performanceNotes: "Strong completion rate. Weak CTA — need to test alternative.",
    createdAt: "2026-04-10",
    updatedAt: "2026-04-15",
    thumbnail: "/workbench/thumbs/scene-tea.jpg",
    body: "[Scene 1: 0-3s] Time-lapse: person tossing at night vs. sleeping peacefully.\n[Scene 2: 3-8s] 'Sleep reset isn't about sleeping more. It's about restoring the signal.'\n[Scene 3: 8-15s] Explain cortisol-melatonin rhythm. Visual: sunrise/sunset cycle.\n[Scene 4: 15-20s] Eastaura approach: herbal support + circadian environment + acupuncture for nervous system regulation.\n[Scene 5: 20-25s] '5 days to reset the pattern. The rest is maintenance.'\n[CTA] Download free Sleep Reset Guide.",
    topics: ["Sleep Reset", "Circadian Rhythm", "Education"],
    platforms: ["YouTube Shorts", "TikTok"],
  },
  {
    id: "content_006",
    title: "5-Day Shanghai + Hangzhou Pilot Flow",
    type: "short_video_script",
    channel: "TikTok",
    campaign: "Pilot Offer Explainer",
    cta: "Start Safety Intake",
    complianceStatus: "approved",
    publishStatus: "scheduled",
    sourceCode: "tiktok_pilot_flow_001",
    performanceNotes: "Clarifies that this is a curated concierge pilot, not a sightseeing package.",
    createdAt: "2026-04-18",
    updatedAt: "2026-04-24",
    thumbnail: "/workbench/thumbs/scene-pavilion.jpg",
    body: "[Scene 1: 0-3s] '5 days. Here is exactly what happens.'\n[Scene 2: 3-8s] Day 1: Shanghai arrival, transfer, orientation, rest.\n[Scene 3: 8-13s] Day 2: Translator-supported TCM-informed wellness consultation.\n[Scene 4: 13-18s] Day 3-4: Bodywork, breath, tea, slow Hangzhou wellness culture day.\n[Scene 5: 18-23s] Day 5: Summary, follow-up suggestions, departure.\n[Scene 6: 23-25s] 'Not medical care. A safety-screened reset experience.'\n[CTA] Start safety intake.",
    topics: ["Pilot Offer", "Shanghai", "Hangzhou"],
    platforms: ["TikTok", "Instagram Reels", "YouTube Shorts"],
  },
  {
    id: "content_007",
    title: "Weekly Brief — Sleep Edition: April 20",
    type: "newsletter",
    channel: "Newsletter",
    campaign: "Newsletter Sleep Series",
    cta: "Read Full Issue",
    complianceStatus: "approved",
    publishStatus: "published",
    sourceCode: "newsletter_sleep_apr20",
    performanceNotes: "Open rate 42%, click rate 8.3%. Above benchmark.",
    createdAt: "2026-04-19",
    updatedAt: "2026-04-20",
    thumbnail: "/workbench/thumbs/newsletter.jpg",
    body: "This week's focus: the difference between sleep deprivation and circadian disruption.\n\n- Case snapshot: executive who 'slept 8 hours' but woke exhausted\n- TCM lens: why time of day matters more than duration\n- Practical tip: 48-hour screen curfew before arrival\n- Next week: herbal support vs. supplement stacking\n\n[CTA] Reply with your sleep question for next edition.",
    topics: ["Newsletter", "Sleep", "Circadian"],
    platforms: ["Newsletter"],
  },
  {
    id: "content_008",
    title: "No Chinese Required — Full English Support",
    type: "short_video_script",
    channel: "Instagram Reels",
    campaign: "Barrier Breaker Series",
    cta: "Check Language Options",
    complianceStatus: "approved",
    publishStatus: "published",
    sourceCode: "reels_no_chinese_001",
    performanceNotes: "Strong engagement from Japan, Korea, and Southeast Asia.",
    createdAt: "2026-04-12",
    updatedAt: "2026-04-16",
    thumbnail: "/workbench/thumbs/scene-consult.jpg",
    body: "[Scene 1: 0-3s] Text: 'I want to try TCM but I don't speak Chinese.'\n[Scene 2: 3-8s] Show bilingual team. English intake, English consultation, English protocol.\n[Scene 3: 8-15s] Testimonials in English. 'I was worried about language. It was never an issue.'\n[Scene 4: 15-20s] Translation support for herbal prescriptions to take home.\n[Scene 5: 20-23s] 'Your only job is to show up. We'll handle the rest.'\n[CTA] Link to language support page.",
    topics: ["Language Barrier", "English Support"],
    platforms: ["Instagram Reels", "YouTube Shorts"],
  },
];

// ─── REVIEW TASKS ───
export const reviewTasks: ReviewTask[] = [
  {
    id: "task_001",
    type: "lead_risk_review",
    priority: "high",
    relatedObject: "Elena Rossi — Lead",
    relatedObjectId: "lead_003",
    aiRecommendation: "Hold sales contact. Acknowledge the intake, request physician clearance, and only discuss non-medical wellness components after human review.",
    status: "pending",
    createdAt: "2026-04-27T09:30:00",
    details: "Hypertension + arrhythmia + Lisinopril + Metoprolol",
  },
  {
    id: "task_002",
    type: "followup_email_approval",
    priority: "medium",
    relatedObject: "James Chen — Lead",
    relatedObjectId: "lead_002",
    aiRecommendation: "Use a consultative reply: explain TCM boundaries, share the safety process, and invite a short fit call.",
    status: "pending",
    createdAt: "2026-04-26T14:20:00",
    details: "Follow-up email for skeptical tech executive",
  },
  {
    id: "task_003",
    type: "content_compliance",
    priority: "high",
    relatedObject: "Stress Recovery Is Not a Vacation",
    relatedObjectId: "content_003",
    aiRecommendation: "Revise medical-adjacent phrasing. Replace outcome claims with experience language and add the non-medical disclaimer before publish.",
    status: "pending",
    createdAt: "2026-04-26T11:00:00",
    details: "Medical-adjacent language in TikTok script",
  },
  {
    id: "task_004",
    type: "script_approval",
    priority: "medium",
    relatedObject: "POV: You come to China for a quiet wellness reset",
    relatedObjectId: "content_001",
    aiRecommendation: "Compliant script. Add subtitles and keep CTA routed to the pilot safety intake.",
    status: "approved",
    createdAt: "2026-04-24T10:15:00",
    details: "Instagram Reels script for POV series",
  },
  {
    id: "task_005",
    type: "notification_priority",
    priority: "urgent",
    relatedObject: "Pilot Fit Call — Anna Kowalski",
    relatedObjectId: "notif_005",
    aiRecommendation: "Consultation reminder is not confirmed. Verify contact details and prepare manual outreach before the Apr 29 fit call.",
    status: "pending",
    createdAt: "2026-04-27T08:00:00",
    details: "Consultation reminder email bounced",
  },
  {
    id: "task_006",
    type: "lead_risk_review",
    priority: "medium",
    relatedObject: "Olivia Brown — Lead",
    relatedObjectId: "lead_008",
    aiRecommendation: "Medium risk. Keep the offer lifestyle-focused, note HRT as a review item, and avoid any herbal or treatment suggestions.",
    status: "pending",
    createdAt: "2026-04-27T12:00:00",
    details: "HRT + menopause-related sleep issues",
  },
  {
    id: "task_007",
    type: "followup_email_approval",
    priority: "low",
    relatedObject: "David Park — Lead",
    relatedObjectId: "lead_004",
    aiRecommendation: "Nurture gently. Share the pilot structure, budget range, and waitlist option without pushing urgency.",
    status: "pending",
    createdAt: "2026-04-25T16:30:00",
    details: "Nurture email for budget-constrained lead",
  },
];

// ─── NOTIFICATIONS ───
export const notifications: Notification[] = [
  {
    id: "notif_001",
    type: "new_lead",
    title: "New intake: Elena Rossi from Italy",
    message: "YouTube Shorts intake submitted. Goals: Whole-Person Balance, Sleep Reset. AI triage flagged medical-boundary review before any sales contact.",
    status: "pending",
    createdAt: "2026-04-27T09:30:00",
    read: false,
    relatedId: "lead_003",
  },
  {
    id: "notif_002",
    type: "high_risk_alert",
    title: "Founder review required",
    message: "Elena Rossi reported arrhythmia and blood-pressure medication. Hold outreach until the review task is resolved.",
    status: "sent",
    createdAt: "2026-04-27T09:35:00",
    read: false,
    relatedId: "lead_003",
  },
  {
    id: "notif_003",
    type: "followup_reminder",
    title: "Proposal follow-up due: Marcus Weber",
    message: "Pilot proposal was sent 3 days ago. Suggested action: gentle email focused on travel window and remaining concerns.",
    status: "pending",
    createdAt: "2026-04-27T08:00:00",
    read: false,
    relatedId: "lead_006",
  },
  {
    id: "notif_004",
    type: "daily_brief",
    title: "Daily Brief - April 27, 2026",
    message: "3 new leads, 2 high-intent, 1 medical-boundary review. 5 review tasks, 4 drafts, 2 follow-ups due today.",
    status: "sent",
    createdAt: "2026-04-27T07:00:00",
    read: true,
    relatedId: "dashboard",
  },
  {
    id: "notif_005",
    type: "failed_email",
    title: "Delivery pending: Anna Kowalski fit call",
    message: "Consultation reminder has not been confirmed. Verify the address and prepare manual outreach before Apr 29.",
    status: "failed",
    createdAt: "2026-04-27T08:00:00",
    read: false,
    relatedId: "lead_005",
  },
  {
    id: "notif_006",
    type: "failed_ai_task",
    title: "Agent check pending: content compliance",
    message: "Medical-boundary scan did not complete for 'Stress Recovery Is Not a Vacation'. Keep the draft in review before publish.",
    status: "failed",
    createdAt: "2026-04-26T11:05:00",
    read: true,
    relatedId: "content_003",
  },
  {
    id: "notif_007",
    type: "new_lead",
    title: "Qualified pilot lead: Sarah Mitchell",
    message: "Instagram Reels intake submitted. Sleep Reset + Stress Recovery, intent 92/100, low risk. Ready for fit-call invite.",
    status: "sent",
    createdAt: "2026-04-26T14:00:00",
    read: true,
    relatedId: "lead_001",
  },
  {
    id: "notif_008",
    type: "followup_reminder",
    title: "Partner question due: Yuki Tanaka",
    message: "Yuki asked about pescatarian meals for the Hangzhou stay. Confirm with hotel partner before replying.",
    status: "pending",
    createdAt: "2026-04-27T10:00:00",
    read: false,
    relatedId: "lead_007",
  },
];

// ─── SKILL FILES ───
export const skillFiles: SkillFile[] = [
  {
    id: "skill_001",
    name: "Brand Voice",
    category: "Foundation",
    updatedAt: "2026-04-20",
    content: `## Eastaura Brand Voice
\n### Core Tone\n- Calm, grounded, and quietly confident\n- Never urgent, never salesy\n- Speak as a practitioner, not a marketer\n- Use sensory language: texture, temperature, rhythm, silence\n\n### What We Say\n- "Your body knows how to recover. We create the conditions."\n- "Five days of structured rest, not five days of treatments."\n- "TCM is a system of balance, not a prescription for cure."\n\n### What We Never Say\n- "Cure", "heal", "fix", "treat" (medical claims)\n- "Guaranteed results"\n- "Doctor-approved" (unless literally true and documented)\n- Discount language, urgency scarcity\n\n### Audience Personas\n1. Burned-out executive (35-50, US/EU/Asia)\n2. Wellness-curious professional (30-45, global)\n3. Post-transition seeker (45-60, life change moment)\n\n### Language Rules\n- English: British or neutral international English\n- Avoid wellness jargon unless explained\n- Use concrete specifics over abstract benefits`,
  },
  {
    id: "skill_002",
    name: "Medical Boundary",
    category: "Compliance",
    updatedAt: "2026-04-18",
    content: `## Medical Boundary Policy
\n### Principle\nEastaura provides wellness experiences. We do not provide medical diagnosis, treatment, or advice.\n\n### Red Flag Conditions (Require Review)\n- Heart conditions, arrhythmia, hypertension on medication\n- Diabetes on insulin\n- Pregnancy\n- Active cancer treatment\n- Post-surgical (within 6 months)\n- Severe mental health conditions\n\n### Approved Language\n- "Support your body's natural balance"\n- "Create conditions for recovery"\n- "Complement your existing health regimen"\n- "Not a substitute for professional medical care"\n\n### Forbidden Language\n- "Treat", "cure", "heal", "fix"\n- "Will reduce blood pressure"\n- "Cures insomnia"\n- "Alternative to medication"\n\n### Process\n1. AI flags medical keywords in intake\n2. Human reviews flagged leads within 4 hours\n3. If high risk: empathetic decline + referral suggestion\n4. If medium risk: modified offer (non-medical components only)\n5. Document all decisions`,
  },
  {
    id: "skill_003",
    name: "Content Strategy",
    category: "Marketing",
    updatedAt: "2026-04-15",
    content: `## Eastaura Content Strategy
\n### Goal\nAttract high-intent overseas clients to the Shanghai arrival + Hangzhou reset pilot through trust-based content.\n\n### Pillars\n1. **Education** - TCM explained simply\n2. **Experience** - POV arrival, tea, rest, translator support\n3. **Trust** - Founder story, safety intake, medical boundaries\n4. **Offer Clarity** - 5-day flow, price range, who it is not for\n\n### Channel Mix\n- Instagram Reels: 40% (primary discovery)\n- TikTok: 20% (hook testing)\n- YouTube Shorts: 15% (search-friendly explainers)\n- LinkedIn: 15% (executive trust-building)\n- Newsletter: 7% (nurture and follow-up)\n- Blog: 3% (deep education)\n\n### Content Rules\n- 80% trust-building, 20% offer\n- Every piece must answer: "Can I trust Eastaura with my travel, safety, and recovery time?"\n- No before/after health claims\n- All guest content is experience-focused, never medical\n- CTA always leads to the safety intake or a fit call`,
  },
  {
    id: "skill_004",
    name: "Short Video Script Rules",
    category: "Marketing",
    updatedAt: "2026-04-22",
    content: `## Short Video Script Rules
\n### Format\n- 20-40 seconds for experience clips\n- 60 seconds max for educational content\n- 3-second hook rule: viewer must know value in 3s\n\n### Structure\n1. Hook (0-3s): Visual + text that stops scroll\n2. Context (3-10s): Establish setting/mood\n3. Core (10-25s): Deliver promise from hook\n4. CTA (25-30s): Single clear action\n\n### Visual Style\n- No stock footage\n- Real Eastaura spaces, real practitioners\n- Natural light preferred\n- Slow, intentional pacing\n- Sound design: ambient, no music or very minimal\n\n### Compliance Checks\n- Script must pass medical boundary scan\n- No health claims in text overlays\n- CTA cannot promise outcomes\n- If showing guest: signed release on file\n\n### POV Series Guidelines\n- Always framed as experience, not testimonial\n- Never show guest faces without consent\n- Focus on spaces, rituals, sensory details\n- "You" language: invites imagination, not expectation`,
  },
  {
    id: "skill_005",
    name: "Lead Review Rules",
    category: "Operations",
    updatedAt: "2026-04-25",
    content: `## Lead Review Rules
\n### Scoring\n- Intent Score (0-100): Based on goal clarity, timeline specificity, budget fit\n- Risk Level: low / medium / high based on medical flags\n\n### Auto-Actions\n- Intent > 80 + Risk LOW -> draft fit-call invite\n- Intent > 80 + Risk MEDIUM -> founder review before outreach\n- Intent 50-80 + Risk LOW -> add to nurture sequence\n- Intent < 50 -> archive with quarterly re-engagement\n- Risk HIGH -> hold, notify founder within 2 hours\n\n### Follow-Up Timing\n- New qualified lead: within 4 hours\n- Post-fit call: proposal or decline within 24 hours\n- Proposal sent: follow-up at 3 days, 7 days, 14 days\n- Nurture: weekly touch for 8 weeks, then monthly\n\n### Data Entry\n- Always log source attribution (campaign, content, channel, UTM)\n- Tag with primary goals for segmentation\n- Note budget range and travel window for pilot fit\n- Record all interactions in timeline`,
  },
  {
    id: "skill_006",
    name: "Follow-up Email Templates",
    category: "Operations",
    updatedAt: "2026-04-21",
    content: `## Follow-up Email Templates
\n### Template: New Qualified Lead\nSubject: Your Eastaura intake — next steps\n\nHi {{name}},\n\nThank you for sharing your goals with us. Based on what you described — {{primary_goals}} — Eastaura could be a meaningful fit.\n\nA few questions to make sure we're the right choice:\n{{custom_questions}}\n\nIf this resonates, the next step is a 20-minute video consultation where we discuss your timeline and what the 5-day structure would look like for your situation.\n\nNo pressure. Just clarity.\n\n[Book Consultation]\n\nWarmly,\n{{sender_name}}\nEastaura\n\n---\n\n### Template: Post-Consultation\nSubject: Your Eastaura proposal\n\nHi {{name}},\n\nThank you for the conversation yesterday. I appreciated your honesty about {{noted_concern}}.\n\nBased on our discussion, I've prepared a personalized 5-day protocol:\n{{proposal_summary}}\n\nThe investment: {{price_range}}\nAvailable dates: {{available_dates}}\n\nTake your time reviewing. I'll check in next week if I haven't heard from you.\n\n[View Full Proposal]\n\nWarmly,\n{{sender_name}}\n\n---\n\n### Template: Nurture (Budget Not Ready)\nSubject: No rush — Eastaura will be here\n\nHi {{name}},\n\nI understand the timing isn't right. That's completely fine.\n\nIn the meantime, I'll send you a short monthly note with:\n- One practical TCM tip you can try at home\n- A glimpse of what's happening at Eastaura\n- Early access when we open new seasonal dates\n\nNo obligation. Unsubscribe anytime.\n\nWarmly,\n{{sender_name}}`,
  },
  {
    id: "skill_007",
    name: "Notification Priority Rules",
    category: "Operations",
    updatedAt: "2026-04-19",
    content: `## Notification Priority Rules
\n### Urgent (Immediate)\n- High-risk lead flagged\n- Failed email to scheduled consultation guest\n- Failed AI task blocking publish\n- Security or privacy incident\n\n### High (Within 2 hours)\n- New high-intent lead\n- Content compliance flagged\n- Follow-up overdue by >24 hours\n- Guest question unanswered >12 hours\n\n### Medium (Within 4 hours)\n- New medium-intent lead\n- Script approval needed\n- Daily brief generation\n- System maintenance window\n\n### Low (Within 24 hours)\n- Weekly reports\n- Content performance summaries\n- Nurture sequence status\n- Non-urgent task completions\n\n### Routing\n- Urgent/High: In-app + email + Feishu\n- Medium: In-app + email\n- Low: In-app digest only\n\n### Quiet Hours\n- 22:00 - 07:00 China time: Urgent only\n- Respect lead timezone for email sends`,
  },
  {
    id: "skill_008",
    name: "Scale Operations",
    category: "Growth",
    updatedAt: "2026-04-10",
    content: `## Scale Operations Playbook
\n### Current Pilot Capacity\n- Target: 3-5 paid pilot clients or one 6-10 person small group\n- Founder handles all sales, reviews, and partner coordination\n- Partners cover licensed TCM delivery, hotel, translation, and transfer support\n\n### Scale Triggers\n- Lead volume > 20 qualified/week for 4 weeks\n- Fit-call booking rate > 45%\n- Proposal conversion rate > 20%\n- Partner SLA stable for 2 pilot cycles\n\n### Scale Options\n1. **Partner Bench** - Add backup clinic, interpreter, hotel, and transfer vendors\n2. **Batch Scheduling** - Fixed monthly arrival windows for Shanghai + Hangzhou\n3. **Assistant Layer** - Scheduling and document chasing, founder still approves decisions\n4. **Small Group Pilot** - Only after private-client flow is reliable\n\n### Maintain Quality\n- Founder reviews every lead and high-risk content item\n- AI handles drafts, human approves outbound messages\n- Keep consultation personal, never templated\n- Medical boundary stays stricter than marketing ambition\n\n### Metrics to Watch\n- Qualified intake rate\n- Fit-call show rate\n- Partner response time\n- Lead quality at scale`,
  },
];

// ─── DASHBOARD DATA ───
export const dashboardStats = {
  newLeadsToday: 3,
  highIntentLeads: 2,
  highRiskLeads: 1,
  pendingReviewTasks: 5,
  contentDraftsWaiting: 4,
  followUpsDueToday: 2,
  weeklyPublished: 12,
  formConversionRate: "4.8%",
  aiTimeSaved: "6.5h",
};

export const funnelData: FunnelStage[] = [
  { stage: "Content Published", count: 18420, percentage: 100 },
  { stage: "Website Visits", count: 1280, percentage: 6.9 },
  { stage: "Intake Started", count: 426, percentage: 33.3 },
  { stage: "Leads Submitted", count: 72, percentage: 16.9 },
  { stage: "Consultations Booked", count: 18, percentage: 25.0 },
];

export const dailyBrief = {
  date: "April 27, 2026",
  items: [
    "3 new leads overnight — 2 high intent, 1 flagged for medical-boundary review",
    "5 review tasks pending before publishing or contacting leads",
    "Anna Kowalski consultation in 2 days — prepare pilot fit and travel-window questions",
    "Shanghai arrival POV series is driving 42% of Intake starts",
    "AI time saved today: 6.5 hours. Focus on consultation prep, risk review, and offer clarity.",
  ],
};

export const topPriorities = [
  "Review Elena Rossi medical risk flag before any sales contact",
  "Approve this week's Shanghai -> Hangzhou pilot content before publishing",
  "Prepare Anna Kowalski consultation notes and 5-day pilot fit questions",
];

export const recentAiSummaries = [
  {
    id: "summary_001",
    leadName: "Sarah Mitchell",
    summary: "High-intent US lead. Sleep + stress goals. Concerns: language, acupuncture safety. Budget fit. No medical flags. Suggested: video consultation link.",
    timestamp: "2 hours ago",
  },
  {
    id: "summary_002",
    leadName: "Elena Rossi",
    summary: "Italian lead. High risk flagged — heart arrhythmia + BP medication. Intent is there but medical boundary review REQUIRED before any contact.",
    timestamp: "1 hour ago",
  },
  {
    id: "summary_003",
    leadName: "Olivia Brown",
    summary: "Australian health professional. Menopause-related sleep issues. On HRT. Medium risk. Needs sensitive framing around medical boundary.",
    timestamp: "6 hours ago",
  },
];

export const topContent = [
  { title: "POV: Shanghai arrival", clicks: "8.7%", leadRate: "4.3%", channel: "Instagram Reels", thumbnail: "/workbench/thumbs/scene-arrival.jpg" },
  { title: "Why Eastaura Doesn't Promise Cures", clicks: "6.2%", leadRate: "6.8%", channel: "LinkedIn", thumbnail: "/workbench/thumbs/linkedin.jpg" },
  { title: "Sleep Reset Explained", clicks: "5.1%", leadRate: "5.6%", channel: "YouTube Shorts", thumbnail: "/workbench/thumbs/scene-tea.jpg" },
  { title: "No Chinese Required", clicks: "4.0%", leadRate: "3.2%", channel: "Instagram Reels", thumbnail: "/workbench/thumbs/scene-consult.jpg" },
];

// ─── CALENDAR EVENTS ───
export const calendarEvents: CalendarEvent[] = [
  { id: "cal_001", title: "POV: Shanghai arrival -> Hangzhou reset", channel: "Instagram Reels", day: 0, time: "09:00", status: "scheduled", thumbnail: "/workbench/thumbs/scene-arrival.jpg", type: "short_video_script" },
  { id: "cal_002", title: "Sleep Reset Explained", channel: "YouTube Shorts", day: 0, time: "10:30", status: "published", thumbnail: "/workbench/thumbs/scene-tea.jpg", type: "short_video_script" },
  { id: "cal_003", title: "Trust & Transparency Post", channel: "LinkedIn", day: 1, time: "08:00", status: "scheduled", thumbnail: "/workbench/thumbs/linkedin.jpg", type: "linkedin_post" },
  { id: "cal_004", title: "No Chinese Required", channel: "Instagram Reels", day: 1, time: "14:00", status: "draft", thumbnail: "/workbench/thumbs/scene-consult.jpg", type: "short_video_script" },
  { id: "cal_005", title: "Weekly Brief — Sleep", channel: "Newsletter", day: 2, time: "07:00", status: "scheduled", thumbnail: "/workbench/thumbs/newsletter.jpg", type: "newsletter" },
  { id: "cal_006", title: "5-Day Shanghai + Hangzhou pilot flow", channel: "TikTok", day: 2, time: "12:00", status: "pending", thumbnail: "/workbench/thumbs/scene-pavilion.jpg", type: "short_video_script" },
  { id: "cal_007", title: "First Consultation Guide", channel: "Blog", day: 3, time: "09:00", status: "published", thumbnail: "/workbench/thumbs/scene-consult.jpg", type: "blog" },
  { id: "cal_008", title: "Stress Recovery POV", channel: "Instagram Reels", day: 4, time: "10:00", status: "draft", thumbnail: "/workbench/thumbs/scene-hotel.jpg", type: "short_video_script" },
  { id: "cal_009", title: "Sleep Reset Shorts", channel: "YouTube Shorts", day: 4, time: "15:00", status: "scheduled", thumbnail: "/workbench/thumbs/scene-tea.jpg", type: "short_video_script" },
  { id: "cal_010", title: "Founder's Story", channel: "LinkedIn", day: 5, time: "08:30", status: "scheduled", thumbnail: "/workbench/thumbs/linkedin.jpg", type: "linkedin_post" },
];

// ─── VIDEO GENERATOR SCENES ───
export const videoScenes: Scene[] = [
  {
    number: 1,
    title: "Hook: Shanghai landing POV",
    thumbnail: "/workbench/thumbs/scene-arrival.jpg",
    caption: "You came to China to finally slow down.",
    narration: "POV shot: landing in Shanghai, then a calm transfer toward Hangzhou. No hype, no packed tour energy.",
    duration: "0-3s",
  },
  {
    number: 2,
    title: "Hangzhou arrival",
    thumbnail: "/workbench/thumbs/scene-walk.jpg",
    caption: "No one rushing you.",
    narration: "Arrival at a quiet Hangzhou wellness space. Warm tea, interpreter greeting, simple orientation.",
    duration: "3-8s",
  },
  {
    number: 3,
    title: "Tea ceremony",
    thumbnail: "/workbench/thumbs/scene-tea.jpg",
    caption: "Your first tea is your first pause.",
    narration: "Close-up: steam rising from ceramic teapot. Keep language non-medical and sensory.",
    duration: "8-15s",
  },
  {
    number: 4,
    title: "Consultation with translator",
    thumbnail: "/workbench/thumbs/scene-consult.jpg",
    caption: "Every word understood.",
    narration: "Translator-supported TCM-informed wellness consultation. Emphasize safety screening and human review.",
    duration: "15-20s",
  },
  {
    number: 5,
    title: "Sunset pavilion",
    thumbnail: "/workbench/thumbs/scene-pavilion.jpg",
    caption: "5 days. Safety screened. Human guided.",
    narration: "Wide shot: quiet pavilion at golden hour. CTA points to Intake, not medical advice.",
    duration: "20-25s",
  },
];

// ─── CHANNEL PERFORMANCE ───
export const channelPerformance: ChannelPerformance[] = [
  { channel: "Instagram Reels", contentCount: 12, clicks: 182, clickRate: "42.7%", leads: 9, leadRate: "50.0%", highIntent: 4, suggestion: "Continue POV experience content" },
  { channel: "TikTok", contentCount: 16, clicks: 156, clickRate: "36.6%", leads: 6, leadRate: "33.3%", highIntent: 2, suggestion: "Test stronger hooks in first 1s" },
  { channel: "YouTube Shorts", contentCount: 10, clicks: 64, clickRate: "15.0%", leads: 2, leadRate: "11.1%", highIntent: 1, suggestion: "SEO-optimized titles needed" },
  { channel: "LinkedIn", contentCount: 6, clicks: 18, clickRate: "4.2%", leads: 1, leadRate: "5.6%", highIntent: 0, suggestion: "Longer-form thought leadership" },
  { channel: "Newsletter", contentCount: 4, clicks: 6, clickRate: "1.4%", leads: 0, leadRate: "0.0%", highIntent: 0, suggestion: "Optimize subject lines and CTAs" },
];

// ─── ATTRIBUTION DATA ───
export const attributionFunnel = [
  { stage: "Impressions", count: 45280, percentage: 100 },
  { stage: "Homepage clicks", count: 2840, percentage: 6.3 },
  { stage: "Website clicks", count: 1280, percentage: 45.1 },
  { stage: "Intake starts", count: 426, percentage: 33.3 },
  { stage: "Intake submissions", count: 72, percentage: 16.9 },
  { stage: "Video consultations", count: 18, percentage: 25.0 },
];

export const attributionKPIs = {
  totalImpressions: "45,280",
  siteClicks: "1,280",
  formSubmissions: 72,
  highIntentLeads: 14,
  videoConsultations: 18,
};

export const effectiveContent = [
  { rank: 1, title: "POV: Shanghai arrival for a 5-day Hangzhou reset", channel: "Instagram Reels", leads: 4, quality: "High", thumbnail: "/workbench/thumbs/scene-arrival.jpg" },
  { rank: 2, title: "Why Eastaura Doesn't Promise Cures", channel: "LinkedIn", leads: 3, quality: "High", thumbnail: "/workbench/thumbs/linkedin.jpg" },
  { rank: 3, title: "Sleep Reset Explained", channel: "YouTube Shorts", leads: 2, quality: "Medium", thumbnail: "/workbench/thumbs/scene-tea.jpg" },
  { rank: 4, title: "No Chinese Required", channel: "Instagram Reels", leads: 2, quality: "Medium", thumbnail: "/workbench/thumbs/scene-consult.jpg" },
  { rank: 5, title: "5-Day Shanghai + Hangzhou pilot flow", channel: "TikTok", leads: 1, quality: "Low", thumbnail: "/workbench/thumbs/scene-pavilion.jpg" },
];
